# Dockerfile for guacamole, forked from oznu/docker-guacamole
#
# Maintained by Antoine Besnier <Contact me via Github>
#
# 2022-12-19 - Changelog maintained in README.md

ARG BASE  
FROM ${BASE}

ARG PG_VERSION
ENV PG_MAJOR=${PG_VERSION}
ENV PATH=/usr/lib/postgresql/${PG_MAJOR}/bin:$PATH

RUN apt-get update && apt-get install --no-install-recommends postgresql-${PG_MAJOR} -y \
    && apt-get --purge autoremove -y \
      apt-transport-https \
      binutils \
      ca-certificates \
      curl \
      git \
      gnupg2 \
      gpg \
      lsb-release \
      make \
      software-properties-common \
    && apt-get autoremove --purge -y \
    && apt-get autoclean -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* /var/tmp/* ~/.m2 /git
